//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int IdEmployee { get; set; }
        public System.DateTime DateVersement { get; set; }
        public System.DateTime DateDebutContrat { get; set; }
        public Nullable<int> IdAbsence { get; set; }
        public Nullable<int> IdConges { get; set; }
        public Nullable<int> IdMission { get; set; }

        public Paiement(int idEmployee, DateTime dateVersement, DateTime dateDebutContrat, int? idAbsence, int? idConges, int? idMission)
        {
            IdEmployee = idEmployee;
            DateVersement = dateVersement;
            DateDebutContrat = dateDebutContrat;
            IdAbsence = idAbsence;
            IdConges = idConges;
            IdMission = idMission;
        }

        public virtual Absence Absence { get; set; }
        public virtual Conge Conge { get; set; }
        public virtual Contrat Contrat { get; set; }
        public virtual Mission Mission { get; set; }
    }
}
