//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_Management.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int IdUtilisateur { get; set; }
        public string NomUtilisateur { get; set; }
        public string MotDePasse { get; set; }

        public Utilisateur(int idUtilisateur, string nomUtilisateur, string motDePasse)
        {
            IdUtilisateur = idUtilisateur;
            NomUtilisateur = nomUtilisateur;
            MotDePasse = motDePasse;
        }

        public virtual Employee Employee { get; set; }
    }
}
